[package]
name = "fastxfix"
version = "0.1.0"
edition = "2024"
description = ""
documentation = ""
repository = ""
categories = []
keywords = []
license = "MIT"

[dependencies]
rayon = "1.10"

[dev-dependencies]
ya-rand = "1"
