name: ci
on: [pull_request, push]

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [macos-latest,
             ubuntu-24.04-arm,
             ubuntu-latest,
             windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Enable full CPU feature set
      run: echo "RUSTFLAGS=-C target-cpu=native" >> "$GITHUB_ENV"
    - name: Update dependencies
      run: cargo update
    - name: Run tests
      run: cargo test
