name: ci
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
        - os: ubuntu-24.04-arm
        - os: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Enable full CPU feature set
      run: echo "RUSTFLAGS=-Ctarget-cpu=native" >> "$GITHUB_ENV"
    - name: Build tests
      run: cargo test --verbose --no-run
    - name: Run tests
      run: cargo test --verbose
